# Generated by Django 4.2 on 2024-01-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='токен верификации'),
        ),
    ]
